 language: node_js
 node_js:
   - "5.0"
   - "4.2"
   - "4.0"
   - "0.12"
   - "0.10"
   - "0.8"
 branches:
 only:
  - master
 notifications:
  email:
   - joaquim.serafim@gmail.com
 script: npm test
